spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aodegw?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      name: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      #初始化时建立的物理连接数
      initialSize: 5
      #最小连接池数
      minIdle: 5
      #最大连接池数
      maxActive: 20
      #获取连接时最大等待时间
      maxWait: 6000
      #线程检测连接时间间隔
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      #用来检测连接是否有效的sql语句
      validationQuery: SELECT id FROM admin
      #申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery，检测连接是否有效
      testWhileIdle: true
      #申请连接时是否使用validationQuery检测连接的有效性
      testOnBorrow: false
      #归还连接时是否使用validationQuery检测连接的有效性
      testOnReturn: false
      #是否缓存PreparedStatements
      poolPreparedStatements: true
      #最大缓存数
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update


